# Generated by Django 2.0 on 2017-12-30 17:20

from django.db import migrations
from django.conf import settings

from ..sites import add_or_update_ambition_sites


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_or_update_ambition_sites),
    ]
